package dsparq.partitioning.format;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 * This class is used to find out the count of
 * edges from the output of hadoop job which generates
 * input file for METIS. This value is required for METIS.
 * @author Raghava
 *
 */
public class GraphStats {
	
	public long countEdges(String path) throws Exception {
		File inputData = new File(path);
		FileReader fileReader = new FileReader(inputData);
		BufferedReader reader = new BufferedReader(fileReader);		
		long edgeCount = 0;
		
		String line;
		try {
			while((line = reader.readLine()) != null) {
				line = line.trim();
				if(line.isEmpty())
					continue;
				String[] tokens = line.split("\\s");
				edgeCount += tokens.length;
			}
		}
		finally {
			if(reader != null)
				reader.close();
		}		
		return edgeCount/2;
	}

	public static void main(String[] args) throws Exception {
		if(args.length != 1) {
			throw new Exception("provide path to the file " +
					"generated by hadoop as input for METIS");
		}
		System.out.println("No of edges: " + new GraphStats().countEdges(args[0]));
		System.out.println("For no of vertices check the last line of " +
				"vertex-part-? file");
	}

}
